name: zarr-ometiff
dependencies:
  - pip=22.2.2
  - python=3.11
  - pip:
    - jupyterlab
    - zarr[jupyter]
    - matplotlib
    - multiscale_spatial_image
    - tifffile==2024.1.30
    - dask-image
    # - spatial-image==0.3.0
    # - multiscale-spatial-image==0.11.2
    # - spatialdata==0.0.15
